# Generated by Django 5.2.1 on 2025-05-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adolescent', 'Adolescent'), ('parent', 'Parent')], default='adolescent', max_length=20),
        ),
    ]
