# Generated by Django 5.2 on 2025-05-27 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='occupation',
        ),
    ]
