# Generated by Django 5.2.4 on 2025-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_alter_postreaction_reaction_type_cart_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adolescent', 'Adolescent'), ('parent', 'Parent'), ('admin', 'Admin')], default='adolescent', max_length=20),
        ),
    ]
