export const dummyProducts = [
  {
    id: "organic-menstrual-pads-kit",
    name: "Organic Cotton Menstrual Pads Starter Kit for Teen Girls",
    price: 32.99,
    discountPrice: 24.99,
    description:
      "A comprehensive menstrual care starter kit designed specifically for teenage girls beginning their menstrual journey. Made with 100% organic cotton, these ultra-soft pads provide maximum comfort and protection while being gentle on sensitive skin.",
    features: [
      "24 organic cotton pads (8 day, 8 night, 8 panty liners)",
      "100% organic cotton top sheet - no chemicals or fragrances",
      "Biodegradable and eco-friendly materials",
      "Individual wrappers for discreet carrying",
      "Includes educational booklet about menstrual health",
      "Free period tracking app access with teen-friendly features",
    ],
    benefits: [
      "Hypoallergenic and gentle for sensitive teenage skin",
      "Reduces risk of irritation and infections",
      "Environmentally conscious choice",
      "Builds confidence during first menstrual experiences",
      "Educational resources promote healthy habits",
    ],
    images: [
      "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.7,
    reviewCount: 342,
    category: "Menstrual Care",
    sku: "MC-ORG-001",
    inStock: true,
    stockCount: 156,
    isNew: false,
    isBestseller: true,
    weight: "1.1 lbs",
    dimensions: "8 x 6 x 3 inches",
    materials: "100% organic cotton, plant-based adhesive",
    age: "12-18 years",
    brand: "PureCare",
  },
  {
    id: "teen-acne-skincare-set",
    name: "Gentle Teen Acne Care System - Dermatologist Recommended",
    price: 45.99,
    discountPrice: 39.99,
    description:
      "A complete 3-step skincare system specifically formulated for teenage acne-prone skin. Developed by dermatologists, this gentle yet effective system helps clear existing breakouts while preventing new ones without over-drying delicate teen skin.",
    features: [
      "Gentle foaming cleanser with 0.5% salicylic acid",
      "Alcohol-free toner with niacinamide and zinc",
      "Lightweight moisturizer with SPF 30 protection",
      "Spot treatment gel for targeted acne care",
      "Soft bamboo washcloths (pack of 3)",
      "Step-by-step routine guide with tips for teens",
    ],
    benefits: [
      "Reduces acne breakouts without harsh irritation",
      "Balances oil production naturally",
      "Protects skin from UV damage daily",
      "Builds healthy skincare habits early",
      "Boosts self-confidence during puberty",
    ],
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1570554886111-e80fcca6a029?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 289,
    category: "Skincare",
    sku: "SK-ACN-002",
    inStock: true,
    stockCount: 78,
    isNew: true,
    isBestseller: false,
    weight: "1.8 lbs",
    dimensions: "10 x 8 x 3 inches",
    materials: "Glass bottles, recyclable packaging",
    age: "13-19 years",
    brand: "ClearSkin Teen",
  },
  {
    id: "menstrual-cup-starter-kit",
    name: "Teen Menstrual Cup Starter Kit with Educational Guide",
    price: 28.99,
    discountPrice: null,
    description:
      "An eco-friendly and cost-effective menstrual solution designed specifically for teenagers. This medical-grade silicone cup provides up to 12 hours of protection and can last for years with proper care. Perfect for active teens participating in sports and activities.",
    features: [
      "Medical-grade silicone menstrual cup (size teen/small)",
      "Organic cotton storage bag with drawstring",
      "Sterilizing cup for easy cleaning",
      "Comprehensive insertion and care guide",
      "QR code access to video tutorials",
      "24/7 customer support hotline for questions",
    ],
    benefits: [
      "Environmentally sustainable period solution",
      "Saves money long-term (lasts 2-5 years)",
      "Freedom for sports and swimming",
      "No risk of toxic shock syndrome",
      "Develops body awareness and confidence",
    ],
    images: [
      "https://images.unsplash.com/photo-1599447421416-3414500d18a5?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 156,
    category: "Menstrual Care",
    sku: "MC-CUP-003",
    inStock: true,
    stockCount: 94,
    isNew: false,
    isBestseller: true,
    weight: "0.3 lbs",
    dimensions: "4 x 4 x 6 inches",
    materials: "Medical-grade silicone, organic cotton bag",
    age: "13-19 years",
    brand: "EcoFlow",
  },
  {
    id: "teen-vitamin-immunity-pack",
    name: "Teen Complete Vitamin & Immunity Support Pack",
    price: 42.99,
    discountPrice: 36.99,
    description:
      "A scientifically formulated vitamin pack designed specifically for teenage nutritional needs during crucial development years. Supports immune system, bone health, energy levels, and cognitive function with tasty, easy-to-take gummies and capsules.",
    features: [
      "30-day supply of essential vitamins (A, C, D, E, B-complex)",
      "Calcium and magnesium for bone development",
      "Omega-3 fatty acids for brain health",
      "Probiotics for digestive and immune support",
      "Iron supplement for growing teens (especially girls)",
      "Natural fruit flavors, no artificial colors",
    ],
    benefits: [
      "Supports healthy growth during puberty",
      "Boosts immune system naturally",
      "Improves energy and concentration for school",
      "Supports bone density during peak development",
      "Fills nutritional gaps in teen diets",
    ],
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605792657660-596af9009e82?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.5,
    reviewCount: 203,
    category: "Nutrition & Supplements",
    sku: "VT-IMM-004",
    inStock: true,
    stockCount: 127,
    isNew: true,
    isBestseller: false,
    weight: "1.2 lbs",
    dimensions: "8 x 6 x 4 inches",
    materials: "BPA-free bottles, vegetarian capsules",
    age: "13-18 years",
    brand: "TeenVitality",
  },
  {
    id: "period-comfort-care-bundle",
    name: "Period Comfort & Care Bundle - Complete Relief Kit",
    price: 54.99,
    discountPrice: 47.99,
    description:
      "Everything a teen needs for comfortable periods. This comprehensive bundle includes pain relief, comfort items, and educational resources to help young women manage their menstrual cycle with confidence and ease.",
    features: [
      "Reusable heating pad with washable cover",
      "Herbal period tea blend (chamomile, ginger, raspberry leaf)",
      "Comfortable period underwear (2 pairs, size options)",
      "Natural period pain relief cream with menthol",
      "Period tracking journal with mood and symptom logs",
      "Cozy comfort socks and eye mask for relaxation",
    ],
    benefits: [
      "Natural pain relief without medications",
      "Promotes comfort during difficult periods",
      "Encourages healthy period tracking habits",
      "Reduces anxiety around menstruation",
      "Provides emotional and physical comfort",
    ],
    images: [
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1584308972272-9e4e7685e80f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.9,
    reviewCount: 418,
    category: "Menstrual Care",
    sku: "PC-BDL-005",
    inStock: true,
    stockCount: 43,
    isNew: false,
    isBestseller: true,
    weight: "2.8 lbs",
    dimensions: "12 x 10 x 6 inches",
    materials: "Organic cotton, natural rubber, BPA-free materials",
    age: "12-19 years",
    brand: "ComfortCare",
  },
  {
    id: "natural-deodorant-teen",
    name: "Aluminum-Free Natural Deodorant for Sensitive Teen Skin",
    price: 16.99,
    discountPrice: null,
    description:
      "A gentle, effective natural deodorant specifically formulated for teenagers' changing bodies. Free from aluminum, parabens, and harsh chemicals, this deodorant provides all-day protection while being kind to developing skin.",
    features: [
      "24-hour odor protection with natural ingredients",
      "Aluminum-free formula safe for daily use",
      "Contains coconut oil, shea butter, and essential oils",
      "Available in 3 teen-friendly scents: Fresh Citrus, Lavender Mint, Unscented",
      "Smooth application that won't leave white marks",
      "Biodegradable cardboard tube packaging",
    ],
    benefits: [
      "Safe for sensitive teenage skin",
      "Builds healthy hygiene habits",
      "Environmentally conscious choice",
      "No harsh chemicals or hormone disruptors",
      "Boosts confidence during physical activities",
    ],
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1612198188060-c7c2a3b66eae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.4,
    reviewCount: 167,
    category: "Personal Care",
    sku: "PC-DEO-006",
    inStock: true,
    stockCount: 234,
    isNew: false,
    isBestseller: false,
    weight: "0.4 lbs",
    dimensions: "4 x 2 x 2 inches",
    materials: "Natural ingredients, biodegradable cardboard",
    age: "12-18 years",
    brand: "PureNature",
  },
  {
    id: "teen-mental-health-toolkit",
    name: "Teen Mental Health & Wellness Toolkit with Therapy Workbook",
    price: 37.99,
    discountPrice: 29.99,
    description:
      "A comprehensive mental health resource designed specifically for teenagers facing anxiety, depression, or everyday stress. Created by licensed therapists, this toolkit provides practical strategies and coping mechanisms for emotional wellness.",
    features: [
      "128-page therapeutic workbook with CBT exercises",
      "Anxiety and stress management technique cards",
      "Mood tracking journal with guided prompts",
      "Mindfulness meditation audio downloads",
      "Crisis resource cards with hotline numbers",
      "Self-care checklist and daily routine planner",
    ],
    benefits: [
      "Develops healthy coping mechanisms",
      "Reduces anxiety and depressive symptoms",
      "Builds emotional intelligence and self-awareness",
      "Provides immediate access to mental health resources",
      "Empowers teens to take control of their mental health",
    ],
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1598520106626-998c2ba554d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1598520105856-794b67a0c22f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1603204077167-2fa0397f591d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.8,
    reviewCount: 312,
    category: "Mental Health & Wellness",
    sku: "MH-TLK-007",
    inStock: true,
    stockCount: 67,
    isNew: true,
    isBestseller: true,
    weight: "1.5 lbs",
    dimensions: "9 x 7 x 2 inches",
    materials: "Recycled paper, eco-friendly inks",
    age: "13-19 years",
    brand: "MindfulYouth",
  },
  {
    id: "sports-nutrition-teen-pack",
    name: "Teen Athlete Nutrition & Hydration Performance Pack",
    price: 48.99,
    discountPrice: 42.99,
    description:
      "Specially designed for active teenagers participating in sports and physical activities. This pack provides clean energy, proper hydration, and recovery support to help teen athletes perform their best while maintaining healthy development.",
    features: [
      "Natural energy drink mix (30 servings, 3 flavors)",
      "Post-workout protein powder (chocolate, vanilla)",
      "Electrolyte tablets for hydration (60 tablets)",
      "Healthy snack bars with whole grains and fruits (12 bars)",
      "BPA-free shaker bottle with measurement marks",
      "Teen athlete nutrition guide and meal planning tips",
    ],
    benefits: [
      "Sustained energy for sports performance",
      "Supports muscle recovery and growth",
      "Maintains proper hydration during activities",
      "Teaches healthy nutrition habits for life",
      "Improves athletic performance naturally",
    ],
    images: [
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1605792657660-596af9009e82?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      "https://images.unsplash.com/photo-1559757175-0eb30cd8c063?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
    ],
    rating: 4.6,
    reviewCount: 189,
    category: "Sports & Nutrition",
    sku: "SN-ATH-008",
    inStock: true,
    stockCount: 89,
    isNew: false,
    isBestseller: false,
    weight: "3.2 lbs",
    dimensions: "12 x 8 x 6 inches",
    materials: "BPA-free containers, natural ingredients",
    age: "13-18 years",
    brand: "YouthSport",
  },
];

export const getProductById = (id: string) => {
  const product = dummyProducts.find((product) => product.id === id);
  return product || dummyProducts[1];
};
